# Generated by Django 4.1.7 on 2023-03-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(default='Automation Ranking', max_length=200)),
                ('sheet_url', models.CharField(max_length=200)),
            ],
        ),
    ]
