# Generated by Django 4.1.7 on 2023-03-14 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesheet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='created_at'),
        ),
    ]
